-- Teacher salary invoice workflow and teacher salary QR metadata.

ALTER TYPE "SalaryStatus" ADD VALUE IF NOT EXISTS 'NEEDS_PAYMENT';
ALTER TYPE "SalaryStatus" ADD VALUE IF NOT EXISTS 'PAID';

ALTER TABLE "teacher_profiles"
  ADD COLUMN IF NOT EXISTS "salaryQrCodeUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "salaryQrCodeStorageKey" TEXT;

ALTER TABLE "salaries"
  ADD COLUMN IF NOT EXISTS "totalPrimarySessions" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "totalExtraSessions" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "totalPresentCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "totalAbsentUnexcusedCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "totalBillableStudentSessions" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "paidAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "paidBy" TEXT;

ALTER TABLE "salary_items"
  ADD COLUMN IF NOT EXISTS "primarySessionsTaught" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "extraSessionsTaught" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "presentCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "absentUnexcusedCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "billableStudentSessions" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "tuitionPerSession" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "salaryAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "cashCollected" DOUBLE PRECISION NOT NULL DEFAULT 0;
